# Use the Node base image for platform ARM/v8 for the build process
FROM --platform=linux/arm64 node:18.18.0 as builder

# Define a Build-Time Variable
ARG API_HTTPS
ARG API_URL
ARG API_PORT

# Set the working directory inside the container
WORKDIR /matrix-door-phone-frontend

# Copy the package.json and package-lock.json into the container
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the entire project content into the container
COPY . .

# Build the application with Parcel
RUN npm run build

# Use an Nginx image as a base for the production environment
FROM --platform=linux/arm64 nginx:latest

# Set workdir
WORKDIR /matrix-door-phone-frontend

# Set the environment variable with the value of the Build-Time Variable
ENV API_HTTPS=$API_HTTPS
ENV API_URL=$API_URL
ENV API_PORT=$API_PORT

# Copy the built application from the build stage into the Nginx container
COPY --from=build /matrix-door-phone-client/dist /usr/share/nginx/html

#COPY hosts /etc/hosts
#COPY custom.conf /etc/nginx/conf.d/default.conf

# Start the Nginx server
CMD ["nginx", "-g", "daemon off;"]

# Set the port that Nginx should listen on (default port 80)
EXPOSE 80
EXPOSE 443