# Use the Node base image for ARM/v8 with the specific version for the build process
FROM node:18.18.0 as builder

# Set the working directory inside the container
WORKDIR /matrix-door-phone-backend

# Copy package.json and package-lock.json (if present)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the source code into the container's working directory
COPY . .

# Run the build script (tsc)
RUN npm run build

# Use a new clean Node base image for ARM/v8 with the specific version for the runtime environment
FROM node:18.18.0

WORKDIR /matrix-door-phone-backend

# Copy only the built files and the files required for runtime
COPY --from=builder /matrix-door-phone-backend/dist ./dist
COPY package*.json ./

# Install only production dependencies
RUN npm install --only=production

# Set the environment variable for Node.js to use the experimental flag
ENV NODE_OPTIONS="--experimental-specifier-resolution=node"

# Expose Port 5000
EXPOSE 5000

# Start the application
CMD ["node", "dist/app.js"]
