# Verwenden einer spezifischen Version von MySQL für Konsistenz
FROM arm64v8/mysql:8.0.33

# Setzen von Umgebungsvariablen für die MySQL-Konfiguration
ENV MYSQL_DATABASE=matrixDoorPhone
ENV MYSQL_USER=appuser
ENV MYSQL_PASSWORD=pass
ENV MYSQL_ROOT_PASSWORD=pass
ENV MYSQL_RANDOM_ROOT_PASSWORD=yes
ENV MYSQL_ONETIME_PASSWORD=yes

# Kopieren des initialen SQL-Skripts in das Container-Image
COPY sql/MatrixDoorPhone.sql /docker-entrypoint-initdb.d/init.sql

# MYSQL_PORT ändern, um Standardports zu vermeiden (erhöht die Sicherheit)
EXPOSE 3306