name: Deploy main branch to docker hub

on:
  push:
    tags:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          platforms: linux/arm/v8
          push: true
          tags: stephan811d/docker-nginx-matrix-door-phone-client:latest
          target: production
          dockerfile: Dockerfile-arm64v8
          build-args: |
            API_HTTPS=${{ vars.API_HTTPS }}
            API_URL=${{ vars.API_URL }}
            API_PORT=${{ vars.API_PORT }}
